# Predicting Online Game Behavior Dataset

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
df = pd.read_csv('online_gaming_behavior_dataset.csv')

In [3]:
df.head()

PlayerID  Age  Gender Location GameGenre  PlayTimeHours  InGamePurchases  \
0      9000   43    Male    Other  Strategy      16.271119                0   
1      9001   29  Female      USA  Strategy       5.525961                0   
2      9002   22  Female      USA    Sports       8.223755                0   
3      9003   35    Male      USA    Action       5.265351                1   
4      9004   33    Male   Europe    Action      15.531945                0   

  GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  PlayerLevel  \
0         Medium                6                        108           79   
1         Medium                5                        144           11   
2           Easy               16                        142           35   
3           Easy                9                         85           57   
4         Medium                2                        131           95   

   AchievementsUnlocked EngagementLevel  
0                    25          Medium  
1                    10          Medium  
2                    41            High  
3                    47          Medium  
4                    37          Medium

In [4]:
df.describe()

PlayerID           Age  PlayTimeHours  InGamePurchases  \
count  40034.000000  40034.000000   40034.000000     40034.000000   
mean   29016.500000     31.992531      12.024365         0.200854   
std    11556.964675     10.043227       6.914638         0.400644   
min     9000.000000     15.000000       0.000115         0.000000   
25%    19008.250000     23.000000       6.067501         0.000000   
50%    29016.500000     32.000000      12.008002         0.000000   
75%    39024.750000     41.000000      17.963831         0.000000   
max    49033.000000     49.000000      23.999592         1.000000   

       SessionsPerWeek  AvgSessionDurationMinutes   PlayerLevel  \
count     40034.000000               40034.000000  40034.000000   
mean          9.471774                  94.792252     49.655568   
std           5.763667                  49.011375     28.588379   
min           0.000000                  10.000000      1.000000   
25%           4.000000                  52.000000     25.000000   
50%           9.000000                  95.000000     49.000000   
75%          14.000000                 137.000000     74.000000   
max          19.000000                 179.000000     99.000000   

       AchievementsUnlocked  
count          40034.000000  
mean              24.526477  
std               14.430726  
min                0.000000  
25%               12.000000  
50%               25.000000  
75%               37.000000  
max               49.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40034 entries, 0 to 40033
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   PlayerID                   40034 non-null  int64  
 1   Age                        40034 non-null  int64  
 2   Gender                     40034 non-null  object 
 3   Location                   40034 non-null  object 
 4   GameGenre                  40034 non-null  object 
 5   PlayTimeHours              40034 non-null  float64
 6   InGamePurchases            40034 non-null  int64  
 7   GameDifficulty             40034 non-null  object 
 8   SessionsPerWeek            40034 non-null  int64  
 9   AvgSessionDurationMinutes  40034 non-null  int64  
 10  PlayerLevel                40034 non-null  int64  
 11  AchievementsUnlocked       40034 non-null  int64  
 12  EngagementLevel            40034 non-null  object 
dtypes: float64(1), int64(7), object(5)
memory usag

In [6]:
missing_data = df.isnull().sum()
print(missing_data)

PlayerID                     0
Age                          0
Gender                       0
Location                     0
GameGenre                    0
PlayTimeHours                0
InGamePurchases              0
GameDifficulty               0
SessionsPerWeek              0
AvgSessionDurationMinutes    0
PlayerLevel                  0
AchievementsUnlocked         0
EngagementLevel              0
dtype: int64


In [7]:
duplicated_data = df.duplicated().sum()
print(duplicated_data)

0


## Encoding data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['GameDifficulty'] = le.fit_transform(df['GameDifficulty'])

In [9]:
df.head()

PlayerID  Age  Gender Location GameGenre  PlayTimeHours  InGamePurchases  \
0      9000   43    Male    Other  Strategy      16.271119                0   
1      9001   29  Female      USA  Strategy       5.525961                0   
2      9002   22  Female      USA    Sports       8.223755                0   
3      9003   35    Male      USA    Action       5.265351                1   
4      9004   33    Male   Europe    Action      15.531945                0   

   GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  PlayerLevel  \
0               2                6                        108           79   
1               2                5                        144           11   
2               0               16                        142           35   
3               0                9                         85           57   
4               2                2                        131           95   

   AchievementsUnlocked EngagementLevel  
0                    25          Medium  
1                    10          Medium  
2                    41            High  
3                    47          Medium  
4                    37          Medium

In [10]:
df = pd.get_dummies(df, columns=['Location', 'GameGenre', 'Gender'], drop_first=False)

In [11]:
df.head()

PlayerID  Age  PlayTimeHours  InGamePurchases  GameDifficulty  \
0      9000   43      16.271119                0               2   
1      9001   29       5.525961                0               2   
2      9002   22       8.223755                0               0   
3      9003   35       5.265351                1               0   
4      9004   33      15.531945                0               2   

   SessionsPerWeek  AvgSessionDurationMinutes  PlayerLevel  \
0                6                        108           79   
1                5                        144           11   
2               16                        142           35   
3                9                         85           57   
4                2                        131           95   

   AchievementsUnlocked EngagementLevel  ...  Location_Europe  Location_Other  \
0                    25          Medium  ...            False            True   
1                    10          Medium  ...            False           False   
2                    41            High  ...            False           False   
3                    47          Medium  ...            False           False   
4                    37          Medium  ...             True           False   

   Location_USA  GameGenre_Action  GameGenre_RPG  GameGenre_Simulation  \
0         False             False          False                 False   
1          True             False          False                 False   
2          True             False          False                 False   
3          True              True          False                 False   
4         False              True          False                 False   

   GameGenre_Sports  GameGenre_Strategy  Gender_Female  Gender_Male  
0             False                True          False         True  
1             False                True           True        False  
2              True               False           True        False  
3             False               False          False         True  
4             False               False          False         True  

[5 rows x 21 columns]

## Splitting the dataset into the Training set and Test set

In [12]:
X = df.drop(columns=['PlayerID', 'EngagementLevel'])
y = df['EngagementLevel']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

## Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Random Forest Classification model on the Training set

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

## Predicting the Test set results

In [16]:
y_pred = classifier.predict(X_test)

## Making the Confusion Matrix and Classification Report

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1765   65  205]
 [  66 1792  235]
 [ 150  170 3559]]


0.8887223679280629

In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        High       0.89      0.87      0.88      2035
         Low       0.88      0.86      0.87      2093
      Medium       0.89      0.92      0.90      3879

    accuracy                           0.89      8007
   macro avg       0.89      0.88      0.88      8007
weighted avg       0.89      0.89      0.89      8007

